version: '3.9'

services:
  db:
    image: postgres:15.2-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-rc1-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data

volumes:
  db-data:
  redis:
