version: '3.9'

services:
  db:
    image: mysql:8.0.33
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '3307:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  redis:
    image: redis:7.2-rc1-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data

volumes:
  redis:
