require('dotenv').config();
import { DataSource } from 'typeorm';
import {
  Category,
  Admin,
  Color,
  Country,
  ShippingMethod,
  Size,
  Upload,
  Product,
  ProductImage,
  User,
  EmailVerification,
  Variation,
  Review,
  Cart,
  CartItem,
  Address,
  Wishlist,
  FaqCategory,
  FAQ,
  Brand,
  Tag,
  ProductTag,
  Promotion,
} from '../entities/';

export const AppDataSource = new DataSource({
  type: 'mysql',
  host: process.env.DB_HOST,
  port: +process.env.DB_PORT,
  username: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME,
  entities: [
    Category,
    Admin,
    Color,
    Country,
    ShippingMethod,
    Size,
    Upload,
    Product,
    ProductImage,
    User,
    EmailVerification,
    Variation,
    Review,
    Cart,
    CartItem,
    Address,
    Wishlist,
    FaqCategory,
    FAQ,
    Brand,
    Tag,
    ProductTag,
    Promotion,
  ],
  synchronize: process.env.NODE_ENV !== 'production',
  migrations: ['dist/migrations/*.js'],
});
``;
